aws:
  numberOfInstances: 9
  instanceType: "m7g.xlarge"
  bucketName: "assignment2-emr"
  jarsPath: "jars"
  logsPath: "logs"
  inputCorpusPath: "s3://datasets.elasticmapreduce/ngrams/books/20090715/heb-all/2gram/data"
  stopWordsPath: "input/heb-stopwords.txt"
  defaultMinNpmi: 0.5
  defaultRelativeMinNpmi: 0.2
  defaultThresholdNpmi: 0.99999
  topNpmi: 10


